url: http://railstutorial-china.org/rails3
pygments: true
markdown: redcarpet
exclude: ['README.md', 'railstutorial-china.sublime-project', 'railstutorial-china.sublime-workspace', 'Gemfile', 'Gemfile.lock', 'CONTRIBUTING.md']
